name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: reverse
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports: [5432:5432]
      cache:
        image: redis:7
        ports: [6379:6379]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Lint
        run: poetry run flake8 app/
      - name: Test
        run: poetry run pytest tests/
      - name: Build Docker images
        run: docker compose -f infra/docker/docker-compose.yml build
